bool CI_getUndervoltage();
void CI_setUnderVoltage(bool undervoltageForSet_b);
bool CI_getOverVoltage();
void CI_serOverVoltage(bool overvoltageForSet_b);
bool CI_getIsFileOpen();
void CI_setIsFileOpen(bool isFileOpenForSet_b);
void CI_getRCTA_Warning(Warning_Feature *RCTA_Warning_ForSet_st);
void CI_setRCTA_Warning(Warning_Feature *RCTA_Warning_ForSet_st);
void CI_getLCW_Warning(Warning_Feature *LCW_Warning_ForSet_st);
void CI_setLCW_Warning(Warning_Feature *LCW_Warning_ForSet_st);
void CI_Read_data();
void CI_Write_data(int option_i, int data_i);
unsigned char CI_getSpeed();
void CI_setSpeed(unsigned char speed);
unsigned char CI_getGear();
void CI_setGear(unsigned char gear);
unsigned char CI_getAngle();
void CI_setAngle(unsigned char angle);
unsigned char CI_getDistance();
void CI_setDistance(unsigned char distance);
unsigned char CI_getBatteryVoltage();
void CI_setBatteryVoltage(unsigned char battery_voltage);
void CI_getCurrent_ssm_state(enum Ssm current_ssm);
void CI_setCurrent_ssm_state(enum Ssm current_ssm);
void CI_getGlobalErr_st(ErrList GlobalErr);
void CI_setGlobalErr_st(ErrList GlobalErr);
