#define QUAL_TIME_UI 150  // to ms (dont work with float)
#define DEQUAL_TIME_UI 150
#define LOSTCOMM_TIMER_UI 300
#define RUNOUT_TIMER_UI 0
#define BATTERY_CYCLE_TIMER_UI 50
#define NUMBER_OF_ERRORS_C 3
#define LOWER_VOLTAGE_LIMIT_C 8
#define UPPER_VOLTAGE_LIMIT_C 16
#define FILE_NOT_OPEN_B 0
#define FILE_OPEN_B 1
#define UNDERVOLTAGE_FALSE_B 0
#define UNDERVOLTAGE_TRUE_B 1
#define OVERVOLTAGE_FALSE_B 0
#define OVERVOLTAGE_TRUE_B 1